// This is a CLI tool — print is the intended output mechanism.
// ignore_for_file: avoid_print
/// tool/collapse.dart — merges abc_accounting + abc_accounting_impl into a
/// single released artifact at .release/abc_accounting/.
///
/// Run from the workspace root:
///   dart tool/collapse.dart
library;

import 'dart:io';

void main() {
  final rootDir = _workspaceRoot();
  print('Workspace root: $rootDir');

  // ── Step 1: Read contractVersion ───────────────────────────────────────────
  print('\n[1/14] Reading contractVersion from abc_accounting...');
  final contractVersion = _grep(
    File('$rootDir/abc_accounting/lib/src/contract/version.dart')
        .readAsStringSync(),
    RegExp(r"const String contractVersion = '(\S+)';"),
    label: 'contractVersion',
  );
  print('       contractVersion = $contractVersion');

  // ── Step 2: Read contractImplemented ──────────────────────────────────────
  print('\n[2/14] Reading contractImplemented from abc_accounting_impl...');
  final contractImplemented = _grep(
    File('$rootDir/abc_accounting_impl/lib/src/registration.dart')
        .readAsStringSync(),
    RegExp(r"const String contractImplemented = '(\S+)';"),
    label: 'contractImplemented',
  );
  print('       contractImplemented = $contractImplemented');

  // ── Step 3: Compare MAJOR.MINOR ───────────────────────────────────────────
  print('\n[3/14] Comparing MAJOR.MINOR segments...');
  final versionMajorMinor = _majorMinor(contractVersion);
  final implMajorMinor = _majorMinor(contractImplemented);
  if (versionMajorMinor != implMajorMinor) {
    print(
      'ERROR: MAJOR.MINOR mismatch — contractVersion=$contractVersion '
      '($versionMajorMinor) vs contractImplemented=$contractImplemented '
      '($implMajorMinor). They must agree before collapsing.',
    );
    exit(1);
  }
  print('       OK — both at MAJOR.MINOR=$versionMajorMinor');

  // ── Step 4: Create output directory ───────────────────────────────────────
  print('\n[4/14] Creating .release/abc_accounting/lib/src/...');
  final releaseLibSrcPath = '$rootDir/.release/abc_accounting/lib/src';
  Directory(releaseLibSrcPath).createSync(recursive: true);
  print('       Created $releaseLibSrcPath');

  // ── Steps 5-9: Recursive copies ───────────────────────────────────────────
  const copies = <(String, String)>[
    (
      'abc_accounting/lib/src/contract',
      '.release/abc_accounting/lib/src/contract',
    ),
    (
      'abc_accounting_impl/lib/src/api',
      '.release/abc_accounting/lib/src/api',
    ),
    (
      'abc_accounting_impl/lib/src/core',
      '.release/abc_accounting/lib/src/core',
    ),
    (
      'abc_accounting_impl/lib/src/domain',
      '.release/abc_accounting/lib/src/domain',
    ),
    (
      'abc_accounting_impl/lib/src/effects',
      '.release/abc_accounting/lib/src/effects',
    ),
    (
      'abc_accounting_impl/lib/src/runtime',
      '.release/abc_accounting/lib/src/runtime',
    ),
  ];

  var stepNum = 5;
  for (final (src, dst) in copies) {
    print('\n[$stepNum/14] Copying $src → $dst...');
    _copyDirectory(
      Directory('$rootDir/$src'),
      Directory('$rootDir/$dst'),
    );
    print('       Done.');
    stepNum++;
  }

  // ── Step 10: di/ (optional) ───────────────────────────────────────────────
  print(
    '\n[10/14] Copying abc_accounting_impl/lib/src/di → '
    '.release/abc_accounting/lib/src/di (if exists)...',
  );
  final diSrc = Directory('$rootDir/abc_accounting_impl/lib/src/di');
  if (diSrc.existsSync()) {
    _copyDirectory(
      diSrc,
      Directory('$rootDir/.release/abc_accounting/lib/src/di'),
    );
    print('       Done.');
  } else {
    print('       di/ not found — skipping.');
  }

  // ── Step 11: Generate factory.dart ────────────────────────────────────────
  print('\n[11/14] Generating .release/abc_accounting/lib/src/factory.dart...');
  File('$rootDir/.release/abc_accounting/lib/src/factory.dart')
      .writeAsStringSync(
    '// Generated by tool/collapse.dart — do not edit.\n'
    "import 'api/account_ledger.dart';\n"
    "import 'contract/ledger.dart';\n"
    "import 'effects/clock.dart';\n"
    "import 'effects/env.dart';\n"
    "import 'effects/id_generator.dart';\n"
    "import 'effects/repository.dart';\n"
    '\n'
    'LedgerFactory get defaultFactory =>\n'
    '    (id) => AccountLedger.open(_defaultEnv(), id);\n'
    '\n'
    'LedgerEnv _defaultEnv() => (\n'
    '  repo: InMemoryLedgerRepository(),\n'
    '  clock: const SystemClock(),\n'
    '  ids: MonotonicIdGenerator(const SystemClock()),\n'
    ');\n',
  );
  print('       Written.');

  // ── Step 12: Write merged barrel ──────────────────────────────────────────
  print('\n[12/14] Writing .release/abc_accounting/lib/abc_accounting.dart...');
  File('$rootDir/.release/abc_accounting/lib/abc_accounting.dart')
      .writeAsStringSync(
    'library;\n'
    "export 'src/contract/ledger.dart';\n"
    "export 'src/contract/vocabulary.dart';\n"
    "export 'src/contract/version.dart';\n"
    "export 'src/factory.dart';\n",
  );
  print('       Written.');

  // ── Step 13: Write pubspec.yaml ───────────────────────────────────────────
  print('\n[13/14] Writing .release/abc_accounting/pubspec.yaml...');
  final sourcePubspec =
      File('$rootDir/abc_accounting/pubspec.yaml').readAsStringSync();
  final releaseVersion = _extractPubspecField(sourcePubspec, 'version');
  final releaseDescription = _extractPubspecDescription(sourcePubspec);
  // Wrap description in a block scalar (>-) to safely handle colons and
  // special characters that would make an unquoted YAML scalar invalid.
  final indentedDescription = releaseDescription
      .split('\n')
      .map((l) => '  $l')
      .join('\n');
  File('$rootDir/.release/abc_accounting/pubspec.yaml').writeAsStringSync(
    'name: abc_accounting\n'
    'version: $releaseVersion\n'
    'description: >-\n'
    '$indentedDescription\n'
    'environment:\n'
    '  sdk: ">=3.5.0 <4.0.0"\n'
    'dependencies:\n'
    '  fpdart: ^1.2.0\n'
    '  fast_immutable_collections: ^11.0.0\n'
    '  riverpod: ^2.6.0\n',
  );
  print('       Written (version=$releaseVersion).');

  // ── Step 13b: Copy or generate README.md and CHANGELOG.md ─────────────────
  print('\n[13b] Writing release README.md and CHANGELOG.md...');
  final readmeSrc = File('$rootDir/abc_accounting/README.md');
  final readmeDst = File('$rootDir/.release/abc_accounting/README.md');
  if (readmeSrc.existsSync()) {
    readmeDst.writeAsStringSync(readmeSrc.readAsStringSync());
  } else {
    readmeDst.writeAsStringSync(
      '# abc_accounting\n\nThe Ledger domain interface and implementation.\n',
    );
  }
  final changelogSrc = File('$rootDir/CHANGELOG.md');
  final changelogDst = File('$rootDir/.release/abc_accounting/CHANGELOG.md');
  if (changelogSrc.existsSync()) {
    changelogDst.writeAsStringSync(changelogSrc.readAsStringSync());
  } else {
    changelogDst.writeAsStringSync(
      '## $releaseVersion\n\nInitial release.\n',
    );
  }
  print('       Written.');

  // ── Step 14: dart pub get + dart analyze ──────────────────────────────────
  print('\n[14/14] Running dart pub get + dart analyze on .release/abc_accounting/...');
  final dartBin = Platform.resolvedExecutable;

  // pub get must run before analyze to resolve dependencies.
  final pubGetResult = Process.runSync(
    dartBin,
    ['pub', 'get', '--directory', '.release/abc_accounting/'],
    workingDirectory: rootDir,
  );
  if (pubGetResult.exitCode != 0) {
    print('COLLAPSE PUB GET FAILED:\n${pubGetResult.stdout}\n${pubGetResult.stderr}');
    exit(1);
  }

  final analyzeResult = Process.runSync(
    dartBin,
    ['analyze', '.release/abc_accounting/'],
    workingDirectory: rootDir,
  );
  if (analyzeResult.exitCode != 0) {
    print('COLLAPSE ANALYZE FAILED:\nstdout: ${analyzeResult.stdout}\nstderr: ${analyzeResult.stderr}');
    exit(1);
  }
  final stdout = analyzeResult.stdout as String;
  if (stdout.isNotEmpty) {
    print(stdout);
  }

  print('\nCollapse complete.');
  exit(0);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Returns the absolute path of the workspace root (the directory that
/// contains this script's `tool/` folder).
String _workspaceRoot() {
  // Platform.script is .../tool/collapse.dart → parent = tool/ → parent = root
  return File(Platform.script.toFilePath()).parent.parent.path;
}

/// Extracts the first capture group from [pattern] in [source].
/// Exits with an error if the pattern is not found.
String _grep(String source, RegExp pattern, {required String label}) {
  final match = pattern.firstMatch(source);
  if (match == null) {
    print('ERROR: could not find pattern for $label in source.');
    exit(1);
  }
  return match.group(1)!;
}

/// Returns the MAJOR.MINOR portion of a semver string.
String _majorMinor(String semver) => semver.split('.').take(2).join('.');

/// Recursively copies [src] directory into [dst], creating [dst] if absent.
void _copyDirectory(Directory src, Directory dst) {
  if (!src.existsSync()) {
    print('ERROR: source directory does not exist: ${src.path}');
    exit(1);
  }
  dst.createSync(recursive: true);
  for (final entity in src.listSync()) {
    final baseName = entity.path.split(Platform.pathSeparator).last;
    if (entity is File) {
      File('${dst.path}/$baseName')
          .writeAsStringSync(entity.readAsStringSync());
    } else if (entity is Directory) {
      _copyDirectory(entity, Directory('${dst.path}/$baseName'));
    }
  }
}

/// Extracts a simple scalar field from a pubspec.yaml string.
String _extractPubspecField(String yaml, String field) {
  final pattern = RegExp('^$field:\\s*(.+)\$', multiLine: true);
  final match = pattern.firstMatch(yaml);
  if (match == null) {
    print('ERROR: could not find "$field:" in pubspec.yaml.');
    exit(1);
  }
  return match.group(1)!.trim();
}

/// Extracts the description value from a pubspec.yaml string.
/// Handles both single-line and block-scalar (`|`, `>`) forms.
String _extractPubspecDescription(String yaml) {
  // Try block scalar first: description: >\n  text\n
  final blockPattern = RegExp(
    r'^description:\s*[|>][^\n]*\n((?:[ \t]+[^\n]*\n?)+)',
    multiLine: true,
  );
  final blockMatch = blockPattern.firstMatch(yaml);
  if (blockMatch != null) {
    // Collapse continuation lines into a single string.
    return blockMatch
        .group(1)!
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .join(' ');
  }
  // Fall back to inline form.
  return _extractPubspecField(yaml, 'description');
}
